### ISSUE TITLE
Update the roadmap

### ISSUE THREAD

**Issue by tnmygrwl** [NextTechLab/McCarthy-Lab#10]
Can we update the roadmap, check for broken links, structure it a little better? For starters, some of the new resources like [Yannic Kilcher's channel](https://www.youtube.com/channel/UCZHmQk67mSJgfCCTn7xBfew), could be added and Hvass Labs (outdated/dead) could be removed. I have a few great resources in mind but feel free to suggest anything in this thread, we can merge when we have reviewed everything and have enough things to update.

**Comment by kausky** [comment]
I will create a PR if I get the time for this.

**Comment by tkrsh** [comment]
@tanmay7270 we can append some of the following under academic courses

Academic Courses
Deep Learning (with Pytorch)
DS-GA 1008: Deep Learning | SPRING 2020
Introduction to Deep Learning
MIT 6.S191: Introduction to Deep Learning | 2020
CNNs for Visual Recognition
CS231n: CNNs for Visual Recognition, Stanford | Spring 2019
NLP with Deep Learning
CS224n: NLP with Deep Learning, Stanford | Winter 2019
Deep Reinforcement Learning
CS285: Deep Reinforcement Learning, UC Berkeley | Fall 2020
CS285: Deep Reinforcement Learning, UC Berkeley | Fall 2019
Unsupervised Learning
CS294-158-SP20: Deep Unsupervised Learning, UC Berkeley | Spring 2020
Multi-Task and Meta Learning
Stanford CS330: Multi-Task and Meta Learning | 2019

**Comment by tkrsh** [comment]
@tanmay7270 we can append some of the following under academic courses 

## Academic Courses 

- [Deep Learning (with Pytorch)](https://atcold.github.io/pytorch-Deep-Learning/)
  - DS-GA 1008: Deep Learning | SPRING 2020
- [Introduction to Deep Learning](http://introtodeeplearning.com/)
  - MIT 6.S191: Introduction to Deep Learning | 2020
- [CNNs for Visual Recognition](http://cs231n.stanford.edu)
  - CS231n: CNNs for Visual Recognition, Stanford | Spring 2019
- [NLP with Deep Learning](http://web.stanford.edu/class/cs224n/index.html#schedule)
  - CS224n: NLP with Deep Learning, Stanford | Winter 2019
- [Deep Reinforcement Learning](https://www.youtube.com/playlist?list=PLkFD6_40KJIwhWJpGazJ9VSj9CFMkb79A)
  - CS285: Deep Reinforcement Learning, UC Berkeley | Fall 2020
  - CS285: Deep Reinforcement Learning, UC Berkeley | Fall 2019
- [Unsupervised Learning](https://www.youtube.com/playlist?list=PLwRJQ4m4UJjPiJP3691u-qWwPGVKzSlNP)
  - CS294-158-SP20: Deep Unsupervised Learning, UC Berkeley | Spring 2020
- [Multi-Task and Meta Learning](https://www.youtube.com/playlist?list=PLoROMvodv4rMC6zfYmnD7UG3LVvwaITY5)
  - Stanford CS330: Multi-Task and Meta-Learning | 2019

**Comment by kausky** [comment]
@tkrsh I think you can create a PR if you find the time to. that will help a lot :)

**Comment by rimijoker** [comment]
I have made a PR( #12 ), let me know if any more additions or changes are required.

**Comment by tnmygrwl** [comment]
Closed this issue, thanks to everyone for their contributions. (@rimijoker @tkrsh @Aakash-kaushik )
