### ISSUE TITLE
Better security for SSH

### ISSUE THREAD

**Issue by kausky** [NextTechLab/McCarthy-Lab#11]
I am not 100% sure but looks like the SSH for samantha wasn't set up with proper security measures such as a `.pem` key and the script [here](https://github.com/NextTechLab/McCarthy-Lab-roadmap/blob/6d50ca451eef317f515a0aca722e7cba685cb813/useful_scripts/samantha.sh#L1) doesn't seem to take in any `-i` flag or a string password.

**Comment by rimijoker** [comment]
We need to fix that @Aakash-kaushik , also the os I think we are better off using stock ubuntu or PopOS rather than whatever was installed on it. Let's take this up once we reach college.

**Comment by kausky** [comment]
@rimijoker It was budgie if I correctly remember, and yeah a distro choice is completely upon a group discussion, because there could be a million things that need to be set up. And regarding a more secure SSH yeah we can do that easily I guess.

**Comment by tkrsh** [comment]
@Aakash-kaushik  It is a completely secure and highly moderated setup. If you have any queries, please feel free to reach me on slack.

**Comment by rimijoker** [comment]
Irreverent as Sahamtha is currently hibernating.
