### ISSUE TITLE
Research Paper

### ISSUE THREAD

**Issue by sriram98v** [NextTechLab/McCarthy-Lab#5]
The general norm is to submit a paper before you push the code to GitHub. We should do the same.

**Comment by tnmygrwl** [comment]
Makes sense to not show the code beforehand, but in case someone decides to publish after they have pushed the code, they could just pull it down or make it a private repo and release the code again once the paper is accepted.

**Comment by sriram98v** [comment]
In that case it should be mentioned that it is at the risk of the publisher.

**Comment by tnmygrwl** [comment]
Yeah I mean if they didn't think of writing a paper first and someone steals the code 🎉then it's on them. 😆

**Comment by sriram98v** [comment]
Ok then that must be added. Closing the Issue
